### ISSUE TITLE
OS-SIM simulation

### ISSUE THREAD

**Issue by liuxinxjtu** [edward-n-ward/ML-OS-SIM#1]
Hi,@ Edward N. Ward, I'm very interested in your work. I understand that your SIM original data is simulated and generated by yourself. But I have a question about the simulation of the defocused part from the DIV2K dataset, as follows.
![1](https://github.com/edward-n-ward/ML-OS-SIM/assets/45114463/bcda85d8-e09f-4f4a-8f5d-6bbf3d6e4063)

**Comment by edward-n-ward** [comment]
Hi. What question did you have about those lines?

**Comment by liuxinxjtu** [comment]
Yes, How did you choose the defocus layer

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/22/2024 21:55 |
| To | edward-n-ward/ML-OS-SIM ***@***.***> |
| Cc | liuxinxjtu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [edward-n-ward/ML-OS-SIM] OS-SIM simulation (Issue #1) |

Hi. What question did you have about those lines?

**Comment by edward-n-ward** [comment]
That line simply randomly selects a static image from the DIV2K library. `files` is simply the list of available .png files held in the folder, as returned by glob
